#!/bin/bash
read -r -p "Enter the name of the Database: " dbname

if [ ! -d "./databases" ]; then
   mkdir "./databases"
fi

dbpath="./databases/$dbname"

if [ -e "$dbpath" ]; then
   echo "Error: Database already exists."
else
   mkdir "$dbpath"
   echo "The Database is created successfully."
fi
